# Generated by Django 5.0.3 on 2024-03-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='auothor_name',
            new_name='author_name',
        ),
    ]
